Repository BSanchez/Nomic, pull requests merged in 2019-12, with the labels that each got.

#2 Technique - Ajout des codes pour thumb up et down dans "COMMENT JOUER.md"
  COMMENT_JOUER.md
Labels: Technique

#1 301 - Adoption - Ajouter des tags aux règles
  règles/301.md
Labels: Adoption

#3 001 - Invocation de jugement
  jugements/001.md
Labels: Jugement
